# Generated by Django 4.1.3 on 2023-03-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Task',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='In Processing', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='task_desc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
